apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: arc-system
spec:
  project: default
  source:
    repoURL: https://github.com/mbasri/quick-aws-eks
    targetRevision: main
    path: manifests.d/k8s.d/actions-runner-controller/controller/base
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
