apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arc-system

resources:
  - https://github.com/actions/actions-runner-controller/releases/download/gha-runner-scale-set-0.13.0/actions-runner-controller-crds.yaml
