---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exemple
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mbasri/nginx
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true
