apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-test
  namespace: scaling-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaling-test
  template:
    metadata:
      labels:
        app: scaling-test
    spec:
      containers:
      - name: scaling-test
        image: nginx
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
